# Generated by Django 4.1.1 on 2022-09-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("student_id", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("start_time", models.CharField(max_length=255)),
                ("end_time", models.CharField(max_length=255)),
                ("line", models.CharField(max_length=255)),
                ("health_dermatology_ent_one", models.CharField(max_length=255)),
                ("health_dermatology_ent_two", models.CharField(max_length=255)),
                ("health_dermatology_ent_three", models.CharField(max_length=255)),
                (
                    "anesthesia_emergency_ophthalmology_one",
                    models.CharField(max_length=255),
                ),
                (
                    "anesthesia_emergency_ophthalmology_two",
                    models.CharField(max_length=255),
                ),
                (
                    "anesthesia_emergency_ophthalmology_three",
                    models.CharField(max_length=255),
                ),
                (
                    "neurology_psychiatry_infectious_one",
                    models.CharField(max_length=255),
                ),
                (
                    "neurology_psychiatry_infectious_two",
                    models.CharField(max_length=255),
                ),
                (
                    "neurology_psychiatry_infectious_three",
                    models.CharField(max_length=255),
                ),
                ("ethics_radiology_one", models.CharField(max_length=255)),
                ("ethics_radiology_two", models.CharField(max_length=255)),
                ("orthopedics_urology_one", models.CharField(max_length=255)),
                ("orthopedics_urology_two", models.CharField(max_length=255)),
                ("internal", models.CharField(max_length=255)),
                ("surgery", models.CharField(max_length=255)),
                ("gynecology", models.CharField(max_length=255)),
            ],
        ),
    ]
