# Generated by Django 4.1.1 on 2022-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="gender",
            field=models.CharField(default="men", max_length=255),
            preserve_default=False,
        ),
    ]
