# Generated by Django 4.1.1 on 2022-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0002_members_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="pediatric",
            field=models.CharField(default="مرکز طبی", max_length=255),
            preserve_default=False,
        ),
    ]
