# Generated by Django 4.1.1 on 2023-01-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0005_selection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="members",
            name="anesthesia_emergency_ophthalmology_one",
        ),
        migrations.RemoveField(
            model_name="members",
            name="anesthesia_emergency_ophthalmology_three",
        ),
        migrations.RemoveField(
            model_name="members",
            name="anesthesia_emergency_ophthalmology_two",
        ),
        migrations.RemoveField(
            model_name="members",
            name="ethics_radiology_one",
        ),
        migrations.RemoveField(
            model_name="members",
            name="ethics_radiology_two",
        ),
        migrations.RemoveField(
            model_name="members",
            name="gynecology",
        ),
        migrations.RemoveField(
            model_name="members",
            name="health_dermatology_ent_one",
        ),
        migrations.RemoveField(
            model_name="members",
            name="health_dermatology_ent_three",
        ),
        migrations.RemoveField(
            model_name="members",
            name="health_dermatology_ent_two",
        ),
        migrations.RemoveField(
            model_name="members",
            name="neurology_psychiatry_infectious_one",
        ),
        migrations.RemoveField(
            model_name="members",
            name="neurology_psychiatry_infectious_three",
        ),
        migrations.RemoveField(
            model_name="members",
            name="neurology_psychiatry_infectious_two",
        ),
        migrations.RemoveField(
            model_name="members",
            name="orthopedics_urology_one",
        ),
        migrations.RemoveField(
            model_name="members",
            name="orthopedics_urology_two",
        ),
        migrations.RemoveField(
            model_name="members",
            name="password",
        ),
        migrations.RemoveField(
            model_name="members",
            name="pediatric",
        ),
        migrations.AddField(
            model_name="members",
            name="gynocology",
            field=models.CharField(default="N", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="minor_month_three",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="minor_month_two",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="minor_week_one",
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="minor_week_three",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="minor_week_two",
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="ortopedix_one",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="ortopedix_two",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="pack_one",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="pack_three",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="pack_two",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="pediatrics",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="urology_one",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="urology_two",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
