# Generated by Django 4.1.1 on 2023-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0006_remove_members_anesthesia_emergency_ophthalmology_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="minor_month_one",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
