# Generated by Django 4.1.1 on 2023-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0007_members_minor_month_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="hichi",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
