# Generated by Django 4.1.1 on 2023-01-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0008_members_hichi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="members",
            name="hichi",
        ),
    ]
