# Generated by Django 4.1.1 on 2023-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0009_remove_members_hichi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selection",
            name="choice",
        ),
        migrations.AddField(
            model_name="selection",
            name="choice_en",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="selection",
            name="choice_fa",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
