# Generated by Django 4.1.1 on 2023-01-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0010_remove_selection_choice_selection_choice_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selection",
            old_name="choice_en",
            new_name="choice",
        ),
        migrations.RenameField(
            model_name="selection",
            old_name="choice_fa",
            new_name="item_en",
        ),
        migrations.RenameField(
            model_name="selection",
            old_name="item",
            new_name="item_fa",
        ),
    ]
