# Generated by Django 4.1.1 on 2023-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0012_selection_iden"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacity",
            name="gender",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
