# Generated by Django 4.1.1 on 2023-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0014_loggedinuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="selection",
            name="line_c",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
